added

diff --git a/JENKINSFILE b/JENKINSFILE
--- a/JENKINSFILE
+++ b/JENKINSFILE
@@ -1,17 +1,64 @@
+// pipeline {
+//     agent any
+
+//     stages {
+//         stage('Clone') {
+//             steps {
+//                 git branch: 'main',
+//                 url: 'https://github.com/cser-srishti-beaspal/snake_game_maven_project.git'
+//             }
+//         }
+//         stage('Execute') {
+//             steps {
+//                 bat'''mvn clean package'''
+//             }
+//         }
+//     }
+// }
+
 pipeline {
     agent any
-
+    tools {
+        jdk 'JDK17'
+        maven 'Maven3'
+    }
+    environment {
+        IMAGE_NAME = "snake-game"
+        CONTAINER_NAME = "snake-container"
+    }
     stages {
-        stage('Clone') {
+        stage('Clone Repository') {
             steps {
-                git branch: 'main',
-                url: 'https://github.com/cser-srishti-beaspal/snake_game_maven_project.git'
+                git 'https://github.com/cser-srishti-beaspal/snake_game_maven_project.git'
             }
         }
-        stage('Execute') {
+        stage('Build Maven Project') {
             steps {
-                bat'''mvn clean package'''
+                bat 'mvn clean package'
             }
+        }
+        stage('Build Docker Image') {
+            steps {
+                bat 'docker build -t %IMAGE_NAME% .'
+            }
+        }
+        stage('Remove Old Container') {
+            steps {
+                bat 'docker rm -f %CONTAINER_NAME% || exit 0'
+            }
+        }
+        stage('Run Container') {
+            steps {
+                bat 'docker run -d --name %CONTAINER_NAME% %IMAGE_NAME%'
+            }
+        }
+    }
+    post {
+        success {
+            echo 'Pipeline executed successfully!'
+        }
+        failure {
+            echo 'Pipeline failed!'
         }
     }
 }
