updates

diff --git a/JENKINSFILE b/JENKINSFILE
--- a/JENKINSFILE
+++ b/JENKINSFILE
@@ -15,6 +15,45 @@
 //         }
 //     }
 // }
+
+
+// pipeline {
+//     agent any
+
+//     environment {
+//         IMAGE_NAME = "snake-game"
+//         CONTAINER_NAME = "snake-container"
+//     }
+
+//     stages {
+
+//         stage('Build Maven Project') {
+//             steps {
+//                 bat 'mvn clean package'
+//             }
+//         }
+
+//         stage('Build Docker Image') {
+//             steps {
+//                 bat 'docker build -t %IMAGE_NAME% .'
+//             }
+//         }
+
+//         stage('Remove Old Container') {
+//             steps {
+//                 bat 'docker rm -f %CONTAINER_NAME% || exit /b 0'
+//             }
+//         }
+
+//         stage('Run Container') {
+//             steps {
+//                 bat 'docker run -d --name %CONTAINER_NAME% -p 8081:8080 %IMAGE_NAME%'
+//             }
+//         }
+//     }
+// }
+
+
 pipeline {
     agent any
 
@@ -25,11 +64,6 @@ pipeline {
 
     stages {
 
-        stage('Build Maven Project') {
-            steps {
-                bat 'mvn clean package'
-            }
-        }
 
         stage('Build Docker Image') {
             steps {
@@ -39,14 +73,24 @@ pipeline {
 
         stage('Remove Old Container') {
             steps {
-                bat 'docker rm -f %CONTAINER_NAME% || exit /b 0'
+                bat 'docker rm -f %CONTAINER_NAME% || exit 0'    
             }
         }
 
         stage('Run Container') {
             steps {
-                bat 'docker run -d --name %CONTAINER_NAME% -p 8081:8080 %IMAGE_NAME%'
+                bat 'docker run -d --name %CONTAINER_NAME% %IMAGE_NAME%'
             }
+        }
+    }
+
+    post {
+        success {
+            echo 'Pipeline executed successfully!'
+        }
+
+        failure {
+            echo 'Pipeline failed!'
         }
     }
 }
